# Generated by Django 2.0.6 on 2018-07-24 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='昵称')),
                ('phone_1', models.CharField(max_length=20, verbose_name='手机号码1')),
                ('phone_2', models.CharField(max_length=20, verbose_name='手机号码2')),
                ('qq', models.CharField(max_length=20, verbose_name='qq号码')),
                ('wechat', models.CharField(max_length=100, verbose_name='微信号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_user_profile', 'View UserProfile'), ('change_user_profile', 'Change User Profile'), ('remove_user_profile', 'Remove User Profile'), ('delete_user_profile', 'Delete User Profile')),
                'db_table': 'account_user_profile',
                'verbose_name': '用户详细信息',
            },
        ),
        migrations.CreateModel(
            name='UserSalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=10, verbose_name='加密用盐值')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_salt', 'View Salt'), ('change_salt', 'Change Salt'), ('remove_salt', 'Remove Salt'), ('delete_salt', 'Delete Salt')),
                'db_table': 'account_user_salt',
                'verbose_name': '加密用盐值',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='用户网站名称')),
                ('page_count', models.CharField(max_length=20, verbose_name='网站下属导航页面数量')),
            ],
            options={
                'permissions': (('view_user_website', 'View UserWebsite'), ('change_user_website', 'Change User Website'), ('remove_user_website', 'Remove User Website'), ('delete_user_website', 'Delete User Website')),
                'db_table': 'website',
                'verbose_name': '用户收藏网页总览',
            },
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='页面名称')),
                ('data', models.CharField(max_length=100, verbose_name='json数据')),
                ('order', models.CharField(max_length=10, verbose_name='显示顺序')),
                ('user_website_id', models.UUIDField(blank=True, default=None, null=True)),
            ],
            options={
                'permissions': (('view_website_page', 'View Website Page'), ('change_website_page', 'Change Website Page'), ('remove_website_page', 'Remove Website Page'), ('delete_website_page', 'Delete Website Page')),
                'db_table': 'website_page',
                'verbose_name': '网站页面',
            },
        ),
        migrations.CreateModel(
            name='WebsitePanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='导航页中的一栏')),
                ('order', models.CharField(max_length=10, verbose_name='显示顺序')),
                ('user_website_id', models.UUIDField(blank=True, default=None, null=True)),
                ('website_page_id', models.UUIDField(blank=True, default=None, null=True)),
            ],
            options={
                'permissions': (('view_website_panel', 'View Website Panel'), ('change_website_panel', 'Change Website Panel'), ('remove_website_panel', 'Remove Website Panel'), ('delete_website_panel', 'Delete Website Panel')),
                'db_table': 'website_panel',
                'verbose_name': '导航页中一栏',
            },
        ),
        migrations.CreateModel(
            name='WebsiteUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('column', models.CharField(max_length=10, verbose_name='列数')),
                ('line', models.CharField(max_length=10, verbose_name='行数')),
                ('user_website_id', models.UUIDField(blank=True, default=None, null=True)),
                ('website_page_id', models.UUIDField(blank=True, default=None, null=True)),
                ('website_panel_id', models.UUIDField(blank=True, default=None, null=True)),
            ],
            options={
                'permissions': (('view_website_url', 'View Website Url'), ('change_website_url', 'Change Website Url'), ('remove_website_url', 'Remove Website Url'), ('delete_website_url', 'Delete Website Url')),
                'db_table': 'website_url',
                'verbose_name': '网站url',
            },
        ),
    ]
