# Generated by Django 2.0.6 on 2018-07-21 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='昵称')),
                ('phone_1', models.CharField(max_length=20, verbose_name='手机号码1')),
                ('phone_2', models.CharField(max_length=20, verbose_name='手机号码2')),
                ('qq', models.CharField(max_length=20, verbose_name='qq号码')),
                ('wechat', models.CharField(max_length=100, verbose_name='微信号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_profile',
                'verbose_name': '用户详细信息',
                'permissions': (('view_user_profile', 'View UserProfile'), ('change_user_profile', 'Change User Profile'), ('remove_user_profile', 'Remove User Profile'), ('delete_user_profile', 'Delete User Profile')),
            },
        ),
        migrations.CreateModel(
            name='UserSalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=10, verbose_name='加密用盐值')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_salt',
                'verbose_name': '加密用盐值',
                'permissions': (('view_salt', 'View Salt'), ('change_salt', 'Change Salt'), ('remove_salt', 'Remove Salt'), ('delete_salt', 'Delete Salt')),
            },
        ),
    ]
