# Generated by Django 2.0.6 on 2018-06-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='auth_user',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='account_user_profile',
        ),
        migrations.AlterModelTable(
            name='usersalt',
            table='account_user_salt',
        ),
    ]
