# Generated by Django 2.0.6 on 2018-07-25 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersalt',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True, verbose_name='用户信息表'),
        ),
        migrations.AddField(
            model_name='usersalt',
            name='user_id',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True, verbose_name='用户信息表'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersalt',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
