# Generated by Django 2.0.6 on 2018-06-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180623_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersalt',
            old_name='auth_user',
            new_name='user',
        ),
    ]
