# Generated by Django 2.0.6 on 2018-06-17 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_auto_20180617_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='昵称')),
                ('phone_1', models.CharField(max_length=20, verbose_name='手机号码1')),
                ('phone_2', models.CharField(max_length=20, verbose_name='手机号码2')),
                ('qq', models.CharField(max_length=20, verbose_name='qq号码')),
                ('wechat', models.CharField(max_length=100, verbose_name='微信号')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户名',
            },
        ),
        migrations.CreateModel(
            name='UserSalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=10, verbose_name='加密用盐值')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户名',
            },
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
