# Generated by Django 2.0.6 on 2018-07-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180623_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_user_profile', 'View UserProfile'), ('change_user_profile', 'Change User Profile'), ('remove_user_profile', 'Remove User Profile'), ('delete_user_profile', 'Delete User Profile')), 'verbose_name': '用户详细信息'},
        ),
        migrations.AlterModelOptions(
            name='usersalt',
            options={'permissions': (('view_salt', 'View Salt'), ('change_salt', 'Change Salt'), ('remove_salt', 'Remove Salt'), ('delete_salt', 'Delete Salt')), 'verbose_name': '加密用盐值'},
        ),
    ]
