# Generated by Django 2.0.6 on 2018-06-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180617_0442'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='backend_user_profile',
        ),
        migrations.AlterModelTable(
            name='usersalt',
            table='backend_user_salt',
        ),
    ]
