# Generated by Django 2.0.6 on 2018-07-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_userwebsite_websitepage_websitepanel_websiteurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwebsite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='websitepanel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='websiteurl',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserWebsite',
        ),
        migrations.DeleteModel(
            name='WebsitePage',
        ),
        migrations.DeleteModel(
            name='WebsitePanel',
        ),
        migrations.DeleteModel(
            name='WebsiteUrl',
        ),
    ]
