# Generated by Django 2.0.6 on 2018-06-17 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20180617_0450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户详细信息'},
        ),
        migrations.AlterModelOptions(
            name='usersalt',
            options={'verbose_name': '加密用盐值'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='auth_user_profile',
        ),
        migrations.AlterModelTable(
            name='usersalt',
            table='auth_user_salt',
        ),
    ]
