# Generated by Django 2.0.6 on 2018-07-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180728_1506'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
        migrations.AlterModelTable(
            name='usersalt',
            table='auth_user_salt',
        ),
    ]
