# Generated by Django 2.0.6 on 2018-07-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='auth_user_profile',
        ),
    ]
