# Generated by Django 2.0.6 on 2018-08-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180731_1507'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='auth_user_profile',
        ),
    ]
