# Generated by Django 2.0.6 on 2018-07-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=100, verbose_name='用户网站名称'),
        ),
    ]
